name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar permisos de Gradle
        run: chmod +x android/gradlew

      - name: Hacer APK debug
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

      - name: Subir el APK final
        uses: actions/upload-artifact@v4
        with:
          name: MiApp-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk